// <auto-generated />
using Interviu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Interviu.Migrations
{
    [DbContext(typeof(AgreementsContext))]
    [Migration("20201029192601_init5")]
    partial class init5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Interviu.Models.Agreement", b =>
                {
                    b.Property<string>("Cod")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<bool>("AcordPrelucrareDate")
                        .HasColumnType("bit");

                    b.Property<string>("CodJudet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ComunicareEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ComunicareMarketing")
                        .HasColumnType("bit");

                    b.Property<bool>("ComunicarePosta")
                        .HasColumnType("bit");

                    b.Property<bool>("ComunicareSMS")
                        .HasColumnType("bit");

                    b.Property<string>("DenumireCompanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod");

                    b.ToTable("Agreements");
                });
#pragma warning restore 612, 618
        }
    }
}
